### ISSUE TITLE
Make sure the bot conforms to fair use guidelines per version

### ISSUE THREAD

**Issue by pmfischer80** [UnimatrixZeroOne/BibleBot#33]
To outline the issue, this is quoted from https://support.biblegateway.com/hc/en-us/articles/228180427-How-do-I-get-permission-to-use-or-reprint-Bible-content-from-Bible-Gateway-

Your freedom to use or reprint content from a particular Bible is dependent on that Bible's copyright status. The following points explain how copyright works at the Bible Gateway.

1) Content on Bible Gateway falls into one of two categories: works that are in the public domain, and works that are under copyright. You can view a particular Bible's copyright status by clicking on its name here: https://www.biblegateway.com/versions/

2) Public domain Bibles may be used freely, without restriction and without prior permission. Note that these works are in the public domain in the United States. Their copyright status may differ in other countries, so please check your local copyright laws before using them outside the US.

3) Bibles not in the public domain are protected under a copyright. We can't give you blanket permission to use or reprint copyrighted content because that content doesn't belong to Bible Gateway. However, most Bible copyright holders have generous fair use policies in place that let you quote and reprint Bible passages up to a reasonable limit. In many cases, these policies are explained on the Bible's version information page. If there is no policy described there for the Bible you want to use, or if you want to use the Bible content in a way that's not covered by that policy, then you must contact the Bible's publisher for permission to do so. Bible Gateway is not able to grant this permission.

**Comment by vypr** [comment]
Currently working on this.

**Comment by vypr** [comment]
Fixed in a2f8092.
