### ISSUE TITLE
Remove Artifacts Left From Removing Headers / Versenumbers

### ISSUE THREAD

**Issue by pmfischer80** [UnimatrixZeroOne/BibleBot#35]
There are various artifacts leftover from my job of introducing verse number removal and headings removal

One Example a slash from two headings that got combined: https://i.imgur.com/teZLUP4.png

I remember other examples where, in some verse, or between some verses, spaces were omitted because of the verse number removal process.

There may be some other artifacts too.

**Comment by vypr** [comment]
Should be fixed in 017d5c.

**Comment by pmfischer80** [comment]
Code looks good here, nice job.
