### ISSUE TITLE
Bible bot triggering (and trying to pull from apocrypha) when user directly quotes the beginning of Proverbs

### ISSUE THREAD

**Issue by pmfischer80** [UnimatrixZeroOne/BibleBot#36]
Issue can be seen here:

https://i.imgur.com/RiZ2T0O.png

**Comment by pmfischer80** [comment]
Ok well, I guess someone fixed that....
But typing: Wisdom of Solomon 1:1
when you're set to like the ESV creates massive error spam

**Comment by pmfischer80** [comment]
I've isolated the offending formula down to:

Solomon: wisdom

just that will trigger it

**Comment by pmfischer80** [comment]
solomon: wisdom wisdom wisdom
triggers massive spam

**Comment by pmfischer80** [comment]
even just
: wisdom wisdom wisdom
triggers it

**Comment by pmfischer80** [comment]
Bottom lines is, it looks like on a version that doesn't have the apocrypha it spams the error message based on every time "wisdom" is said after a colon

**Comment by pmfischer80** [comment]
Are you sure the core problem here is fixed, I just checked and it triggers
on other apocrypha names as well

If you put a colon followed by whitespace, then the name of a book from the
apocrypha, it triggers the error for apocrypha for each time the book name
was mentioned AND it continues to loop sending the error over and over
maybe 4 times for each time the book name was mentioned.

This of course only happens when it needs to throw an apocrypha error.  On
a version with the apocrypha it recognizes that : [bookname] [bookname]
[bookname] ... is not a valid formula so it doesn't respond.

**Comment by vypr** [comment]
This may be fixed in the next push, I ensured that the book detection scheme had more assurance of a book having actual verses.

**Comment by pmfischer80** [comment]
Did you figure out why it's looping?

**Comment by vypr** [comment]
The fix I've made should cover that as well, although I don't know what is causing the loop.

**Comment by vypr** [comment]
Should be fixed in 4f27ede.

**Comment by pmfischer80** [comment]
Yup, looks like that could certainly cause the problem.
