### ISSUE TITLE
Using Explicit calls to the bot instead of implicit

### ISSUE THREAD

**Issue by pmfischer80** [UnimatrixZeroOne/BibleBot#38]
I've noticed when having conversations using the BibleBot that it's good to introduce the actual text into the conversation, but I think explicit calls might be better because once the verses are introduced, people usually don't want the text again even if they mention the verses again.

I think perhaps having the bot's name @mention'd should trigger it.  This way you can introduce text into the conversation only when you want it.

Adding markup to define an explicit mention would be another way.  Perhaps eventually we could have both... if you @mention the bot it will try to display any verse it finds, otherwise, it will just look for the markup characters

**Comment by vypr** [comment]
I won't do this, because:

1) convenience
2) the method of conversation that would be required for the bot to be "annoying" implicitly

To expound on 2, no one converses like this:
"a: hello i love Genesis 1:1"
"b: in the beginning, eh?"
"a: yep, good ol Genesis 1:1"

**Comment by pmfischer80** [comment]
for number one, who's convenience are you talking about?

for number two, that's really a strawman, people really do recite the verse when they are having theological dialogue about it, especially when they bring up several verses and then recite one of them to expound or reiterate a point.  I've seen it happen.  I've done it!

**Comment by vypr** [comment]
If it becomes a major issue, then I'll deal with it. Until then, the bot is staying implicit.

**Comment by pmfischer80** [comment]
ok
